---
kind: pipeline
name: default

steps:
  - name: tags
    image: alpine/git
    commands:
      - git fetch --tags

  - name: lint
    image: golangci/golangci-lint:latest
    commands:
      - make lint
    depends_on:
      - tags

  - name: test
    image: golang:latest
    commands:
      - make test
    depends_on:
      - tags

  - name: build
    image: goreleaser/goreleaser:v0.162.0
    commands:
      - (cd /tmp; go get -u github.com/go-bindata/go-bindata/...)
      - make build
    depends_on:
      - tags
      - lint
      - test
    when:
      event:
        exclude:
          - tag

  - name: release
    image: goreleaser/goreleaser:v0.162.0
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    commands:
      - goreleaser release --rm-dist
    depends_on:
      - tags
      - lint
      - test
    when:
      event:
        - tag
