---
builds:
  - env:
      - CGO_ENABLED=0

    goos:
      - linux

    goarch:
      - amd64
      - arm

    goarm:
      - 6
      - 7

    ldflags:
      - "-s"
      - "-w"
      - "-extldflags '-static'"
      - "-X go.xsfx.dev/cmd.version={{.Version}}"
      - "-X go.xsfx.dev/cmd.commit={{.ShortCommit}}"
      - "-X go.xsfx.dev/cmd.date={{.Date}}"

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  github:
    owner: xsteadfastx
    name: schnutibox
