---
builds:
  - env:
      - CGO_ENABLED=0

    goos:
      - linux

    goarch:
      - amd64
      - arm

    goarm:
      - 6
      - 7

    ldflags:
      - "-s"
      - "-w"
      - "-extldflags '-static'"
      - "-X go.xsfx.dev/schnutibox/cmd.version={{.Version}}"
      - "-X go.xsfx.dev/schnutibox/cmd.commit={{.ShortCommit}}"
      - "-X go.xsfx.dev/schnutibox/cmd.date={{.Date}}"

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^dev:"
      - "happy linting"

release:
  github:
    owner: xsteadfastx
    name: schnutibox

dockers:
  - dockerfile: build/package/docker/Dockerfile
    goos: linux
    goarch: amd64
    image_templates:
      - ghcr.io/xsteadfastx/schnutibox:latest
      - ghcr.io/xsteadfastx/schnutibox:{{ .Tag }}
      - ghcr.io/xsteadfastx/schnutibox:v{{ .Major}}
